test = {   'name': 'q1_1',
    'points': 1,
    'suites': [   {   'cases': [   {'code': '>>> all_countries.num_rows == 183\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> all_countries.row(23)[0] < all_countries.row(55)[0]\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> all_countries.labels == ("Country", "Earliest Year")\nTrue', 'hidden': False, 'locked': False},
                                   {   'code': '>>> data.where("year", all_countries.row(128)[1]).where("country", all_countries.row(128)[0]).column("cgdpe") != -1\narray([ True])',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> data.where("year", all_countries.row(134)[1]).where("country", all_countries.row(134)[0]).column("cgdpe") != -1\narray([ True])',
                                       'hidden': False,
                                       'locked': False},
                                   {   'code': '>>> data.where("year", all_countries.row(134)[1] - 1).where("country", all_countries.row(134)[0]).column("cgdpe") == -1\narray([ True])',
                                       'hidden': False,
                                       'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
