test = {   'name': 'q6_1',
    'points': None,
    'suites': [   {   'cases': [   {'code': '>>> str(P_S) == "P_S"\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> str(Q_S) == "Q_S"\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(P_S) == sympy.Symbol\nTrue', 'hidden': False, 'locked': False},
                                   {'code': '>>> type(Q_S) == sympy.Symbol\nTrue', 'hidden': False, 'locked': False}],
                      'scored': True,
                      'setup': '',
                      'teardown': '',
                      'type': 'doctest'}]}
